### PR TITLE
Reintegrate skeleton-tf-module into Repository

### PR DESCRIPTION
**Pull request by mcdonnnj**
# 

## 🗣 Description

This PR would reintegrate the [cisagov/skeleton-tf-module](https://github.com/cisagov/skeleton-tf-module) skeleton into this repository.

This was done by adding the correct skeleton repository as a remote, pulling from its develop branch, and resolving any conflicts shown. 

```console
git remote add skeleton git@github.com:cisagov/skeleton-tf-module.git
git remote set-url --push skeleton no_push
git pull --allow-unrelated-histories skeleton develop
git status
```

I attempted to flesh out the README a bit with updated example usage, but all the variables for this module are missing descriptions and there is no full-fledged example.

## 💭 Motivation and Context

When this project was created, it does not appear to have been started using our [`skeleton` tool](https://github.com/cisagov/development-guide/tree/develop/project_setup#skeleton-tool-) or the same process manually. This prevents the [`lineage` GitHub Action](https://github.com/cisagov/action-lineage) from automatically generating PRs to ensure downstream repositories are kept up-to-date.

## 🧪 Testing

Automated tests pass.

## 🚥 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by felddy — APPROVED** [review]
Looks good.  Let's make sure to get the new `CODEOWNERS` "lock down" sauce in here.

**Comment by mcdonnnj** [comment]
@felddy With https://github.com/cisagov/skeleton-generic/pull/57 merged, I have brought this repo up-to-date again and that fu is included.

**Comment by mcdonnnj** [comment]
I brought this back up-to-date, replaced repo name references, and fixed the failing GitHub Actions. This should once again be at a merge-able state.

**Comment by mcdonnnj** [comment]
@zenine07 Just calling your attention here in case you didn't notice the review request.

**Comment by zenine07** [comment]
@mcdonnnj Yep, I noticed it, haven't gotten to it because I've been super busy the past several days. This repository is actually one that can be deleted, but I'd like this PR to stick around for awhile as it has great notes that will help me to get the other domain-manager/con-pca repositories up-to-date with the skeletons.

**Comment by zenine07** [comment]
This repo can be deleted now. Nothing has been done on it for a year and the code can't really be referenced anymore effectively as it is out of date.

**Pull request closed without merging**
